### ISSUE TITLE
Accessing minute-level data

### ISSUE THREAD

**Issue by faulconbridge** [nachmore/unBand#11]
Via [Jeff Huang](http://jeffhuang.com/extracting_my_data_from_the_microsoft_band.html) it looks like minute-level data (heart rate, steps, etc.) are uploaded to servers operated by Microsoft rather than being stored locally. These data are then retrieved by a REST GET request, presumably for displaying day and week activity graphs on the phone applications.

Is it possible for unBand to retrieve a user's entire historical dataset at the minute-by-minute level by reusing the Microsoft Health app's authentication token?

**Comment by nachmore** [comment]
No steps yet, see #15, but full minute-by-minute is now included in the full export that was just merged into master.
