### ISSUE TITLE
Only seeing Sleep data

### ISSUE THREAD

**Issue by nachmore** [nachmore/unBand#23]
As per https://twitter.com/bc3tech/status/557258173325664256 some people are only seeing Sleep data in their exports. We need to add some logging to diagnose the issue.

**Comment by bc3tech** [comment]
I have a strong hunch this is a Microsoft problem and not an Unband one. When I go to 'Activity History' in the Band app on my phone I also only see Sleep, not Steps/Calorie.

**Comment by nachmore** [comment]
@bc3tech That's actually expected - to see the history for both of those you need to go into the Tiles for them on the main screen of the app and then scroll down.

The cloud APIs for these are separate from the actual Activity ones - I have the dump of those, I just need to find a neat way of amalgamating the two so that they all come up nicely in the same list. It's definitely on the todo for vNext (by next week hopefully?).

Have you taken and runs or started any workouts? Those should show up in the list (you can verify by starting and stopping a fake one, seeing if it shows up and then deleting it afterwards).

**Comment by nachmore** [comment]
As per our twitter conversation, this is expected - follow #15 for updates on Steps (you can now see them in the list, export should come next)...
