### ISSUE TITLE
Will not display anything but sleep and one workoug

### ISSUE THREAD

**Issue by Noahma** [nachmore/unBand#29]
Whenever I attempt to view data from the band it will only display sleep and one workout in the list of events.  If I uncheck any of the checkboxes and then refresh I get the same list of sleep events, no other data is displayed

**Comment by nachmore** [comment]
Thanks for the bug report - do you actually have any other activities that you've done lately? Steps are not currently working (they are in code, but not in the released version, see issue #15) and the checkboxes not actually doing thing is a recent, known, regression.

**Comment by Noahma** [comment]
Actually, no there are no other activities in my band as of yet.  This actually helps a great ton.  I will look forward to the next version. Thanks!  











From: Oren Nachman
Sent: ‎Sunday‎, ‎February‎ ‎8‎, ‎2015 ‎1‎:‎05‎ ‎AM
To: nachmore/unBand
Cc: Noah Mason





Thanks for the bug report - do you actually have any other activities that you've done lately? Steps are not currently working (they are in code, but not in the released version, see issue #15) and the checkboxes not actually doing thing is a recent, known, regression.

**Comment by nachmore** [comment]
Awesome - stay tuned for the next version which should have your daily activity counters (including steps).
