### ISSUE TITLE
Starbucks card information wiped

### ISSUE THREAD

**Issue by BugBusted** [nachmore/unBand#32]
I noticed that the star bucks card information was wiped.  This occurred after the initial connection with unband.

**Comment by nachmore** [comment]
Weird - I'll take a look, thanks for the report!

**Comment by BugBusted** [comment]
I checked the other band (my wife's) and it had not cleared the starbucks card, but I can't explain why my band had the number erased.  If I encounter the issue again, I'll try and figure out where it happened.

**Comment by nachmore** [comment]
Ok, thanks for the follow up!
