### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JoeNor** [nachmore/unBand#34]
I came across this error. I feel it might be in the works to be addressed

![crash](https://cloud.githubusercontent.com/assets/10967414/6158542/4f8144ca-b219-11e4-9883-53a69aeab10b.JPG)

**Comment by nachmore** [comment]
Is this with the standard version, or have you built from source? In general this is an error with the transport between your machine and the Band (USB cable flicked out etc.) and not something that I can control within unBand (beyond showing a prettier error message).

**Comment by JoeNor** [comment]
Oren, This is the version of Unband I installed from your web site. I do not have the technical skill to build anything like what you did from scratch. The MS windows recognized the Band.    Would that eliminate the transport error you mention. Thanks for your help I am hoping I can get your program to work. It looks it would be a great upgrade to the Band. 

Joe Norton
917 515 5088

**Comment by nachmore** [comment]
Interesting - thanks for following up.

In general that error is coming straight from the Band and not from my software. Can you try plugging the Band into a different USB port? Also, can you make sure that the Band Sync app is closed?

**Comment by JoeNor** [comment]
I tried a different USB port and I checked to make sure the Band Sync App was closed. No luck. Same crash and message. If you have another suggestion I'll gladly try. Thanks

Joe Norton
917 515 5088

**Comment by nachmore** [comment]
Closing this - please open a new bug if this is still happening with the new Band Desktop Sync App and the newest versions of unBand. Thanks!
