### ISSUE TITLE
Option to put battery indicator on the Me tile

### ISSUE THREAD

**Issue by EphraimB** [nachmore/unBand#44]
Add option to put battery indicator on the top right of the Me tile like shown here:
![unband support](https://cloud.githubusercontent.com/assets/10489639/6384274/8e2417ce-bd28-11e4-9dd2-fcc5b6e552ce.jpg)

**Comment by nachmore** [comment]
Sadly this is not something that this project can accomplish - we don't have the ability to influence the code that's actually running on the Band beyond the options that are open from Microsoft.

That said, a little birdie tells me that this is a common request even within Microsoft, so here's hoping the team is listening :)
