### ISSUE TITLE
unBand is unable to find the Desktop App

### ISSUE THREAD

**Issue by ihayesjr** [nachmore/unBand#57]
Every time I start the unBand application, it states that it cannot find the desktop sync app.

**Comment by nachmore** [comment]
1. Do you have the latest Desktop Sync App installed?
2. Where is it installed?

Can you launch unBand (there should be another update), hit Ctrl+C on the message that pops up saying it can't find the Desktop Sync App and then paste it in here as well? Thanks!

**Comment by ihayesjr** [comment]
I just installed both the unBand and Microsoft Band Sync today.
 
It states" Missing file: c:\program files(x86)\Microsoft.Band.Admin.Desktop.dll"
 
It should be looking for it in the C:\Program Files (x86)\Microsoft Band Sync\ directory.
 
Irvin
 
Date: Thu, 5 Mar 2015 11:02:53 -0800

**Comment by ihayesjr** [comment]
I just installed both the unBand and Microsoft Band Sync today.

It states" Missing file: c:\program files(x86)\Microsoft.Band.Admin.Desktop.dll"

It should be looking for it in the C:\Program Files (x86)\Microsoft Band Sync\ directory

Irvin






Sent from Surface





From: Oren Nachman
Sent: ‎Thursday‎, ‎March‎ ‎5‎, ‎2015 ‎2‎:‎02‎ ‎PM
To: nachmore/unBand
Cc: Irvin Hayes Jr




Do you have the latest Desktop Sync App installed?
Where is it installed?

Can you launch unBand (there should be another update), hit Ctrl+C on the message that pops up saying it can't find the Desktop Sync App and then paste it in here as well? Thanks!

**Comment by nachmore** [comment]
Thanks for the details! Please update to the latest and let me know if it's fixed. If not, please paste in the new error message.

**Comment by ihayesjr** [comment]
That fixed it.







From: Oren Nachman
Sent: ‎Thursday‎, ‎March‎ ‎5‎, ‎2015 ‎2‎:‎56‎ ‎PM
To: nachmore/unBand
Cc: Irvin Hayes Jr





Thanks for the details! Please update to the latest and let me know if it's fixed. If not, please paste in the new error message.

**Comment by nachmore** [comment]
Excellent, thanks for the followup!
