### ISSUE TITLE
Tile bug

### ISSUE THREAD

**Issue by rafapeiter** [nachmore/unBand#58]
After update the message is show:

---------------------------

---------------------------
Your Band is hitting a Tile bug that unfortunately unBand cannot work around.

To fix this please remove all of your tiles through the Phone app and the readd them back, this should fix this error. Sadly, unBand will now close.

If it doesn't, please open a bug at https://github.com/nachmore/unBand/issues with the contents of this message (hit Ctrl+C now to copy)

System.ArgumentException: name cannot have length 0.

   em Microsoft.Band.Admin.CargoStrapp.SetName(Guid id, String name)

   em Microsoft.Band.Admin.CargoStrapp..ctor(Guid id, String name, StrappSettings strappSettings, IList`1 images, UInt32 tileImageIndex, IList`1 layouts, Nullable`1 badgeImageIndex)

   em Microsoft.Band.Admin.TileDataExtensions.ToCargoStrapp(TileData data, TileIconRleData icon)

   em Microsoft.Band.Admin.CargoClient.StrappStructToClass(List`1 list)

   em Microsoft.Band.Admin.CargoClient.GetStartStrip()

   em Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>b__251()

   em System.Threading.Tasks.Task`1.InnerInvoke()

   em System.Threading.Tasks.Task.Execute()

--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   em Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>d__252.MoveNext()

--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   em unBand.BandHelpers.BandTiles.<InitAsync>d__1.MoveNext() na d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandTiles.cs:linha 27

--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---

   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   em unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext() na d:\codesanity\oss\unBand\src\unBand\BandHelpers\BandManager.cs:linha 269

--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---

   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nachmore** [comment]
I'm confused by this bug, did you try the workaround listed in the message and it didn't work?

**Comment by rafapeiter** [comment]
Yes, I did still factory reset did not work well.

**Comment by rafapeiter** [comment]
No solution yet?
Before the update this problem did not happen.

**Comment by nachmore** [comment]
To be clear - you removed all of the tiles through the app, then readded them and the issue still happens?

**Comment by EphraimB** [comment]
I just removed all the tiles through the ios app and then readded them and the issue still happens?

**Comment by rafapeiter** [comment]
If I remove all the tiles It works.

**Comment by rafapeiter** [comment]
1) Remove them all from the iOS application.
2) Enter the unBand software.
3) Add the tiles from the iOS application.

It works for me.

**Comment by nachmore** [comment]
Portuguese debugging badge - unlocked! :)

I'm looking to consume this error in a more transparent way...

**Comment by nachmore** [comment]
Actual code in dfbb70f46dd70621967eac94c96977d439952171
