### ISSUE TITLE
GPX - Export - Timezone

### ISSUE THREAD

**Issue by R063R-A-C** [nachmore/unBand#59]
When exporting an activity to gpx, it sould include the timezone in the time tag, ex 2015-03-12T18:47:20**Z**.
Everytime I export an activity I have to replace with the notepad++ the time tag to import it correctly in the Strava platform.

**Comment by iamdabe** [comment]
I've just submitted a fix for this for nachmore to approve.

**Comment by R063R-A-C** [comment]
Thank you, i would to help you everytime I can! 
Regards
