### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by zeke009** [nachmore/unBand#62]
I receive the following message when attempting to install:
An error occurred trying to download 'https://raw.githubusercontent.com/nachmore/unband/clickonce/unBand.application'.

See the setup log file located at 'C:\Users\REMOVED\AppData\Local\Temp\VSDBCA6.tmp\install.log' for more information.

The log contains the following data:
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 6.3.0 {version}
Running checks for package 'Microsoft .NET Framework 4.5 (x86 and x64)', phase BuildList
Reading value 'Version' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read string value '4.5.51650'
Setting value '4.5.51650 {string}' for property 'DotNet45Full_TargetVersion'
The following properties have been set for package 'Microsoft .NET Framework 4.5 (x86 and x64)':
Property: [DotNet45Full_TargetVersion] = 4.5.51650 {string}
Running checks for command 'DotNetFX45\dotNetFx45_Full_x86_x64.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX45\dotNetFx45_Full_x86_x64.exe' is 'Bypass'
Running checks for command 'DotNetFX45\dotNetFx45_Full_setup.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'DotNet45Full_TargetVersion' and value '4.5.50709': true
Result of checks for command 'DotNetFX45\dotNetFx45_Full_setup.exe' is 'Bypass'
'Microsoft .NET Framework 4.5 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://raw.githubusercontent.com/nachmore/unband/clickonce/unBand.application'.

**Comment by nachmore** [comment]
Is this Server or a client SKU of Windows? Have you had any trouble installing other ClickOnce applications?

**Comment by zeke009** [comment]
Sorry, I forgot to post that.
Windows Professional 8.1 64bit

**Comment by zeke009** [comment]
I can't think of any other click once apps I've used. Got a personal favorite to recommend?

**Comment by nachmore** [comment]
This should be a case of simply not being able to grab the file, but then not sure how you'd be able to grab the setup file either. Can you access https://raw.githubusercontent.com/nachmore/unband/clickonce/unBand.application from the machine (it should just show you an xml file)?

**Comment by zeke009** [comment]
Hi Oren,

I am able to load URL in my browser and view the XML file.
________________________________

**Comment by nachmore** [comment]
Can you try this workaround: https://support.microsoft.com/en-us/kb/934387

**Comment by nachmore** [comment]
... although I'm not doing any conscious transitioning between https and http. Still digging.

**Comment by zeke009** [comment]
I came across the KB the other day, but discarded it after seeing I didn’t have that setting checked. I read this tonight and ran the tool, but all it did was register the Windows Installer service: http://blogs.msdn.com/b/astebner/archive/2012/09/05/10346800.aspx.

 

I will have to test on my tablet tomorrow, maybe it’s just a one off issue and my PC happens to be the one.

**Comment by zeke009** [comment]
It works on my tablet (Win8.1 Pro 64-bit). I figure I'll reimage my desktop when Win10 comes around, but is there a way to copy the files over from the tablet?

**Comment by nachmore** [comment]
Thanks for the follow up, wonder what's blocking it on your Desktop? You could, in theory, copy over the installed files and see if that works (search for unband under C:\Users\[user]\AppData\Local\Apps\2.0\). Additionally you could simply build from source. Sorry for the trouble :(

**Comment by slugsgomoo** [comment]
I didn't use the KB, however I had the same issue. I did "run as administrator" on the setup, and it ran through successfully for me.
