### ISSUE TITLE
Skin Temperature Readings

### ISSUE THREAD

**Issue by kasun61** [nachmore/unBand#66]
This is really useful for me and Thank you for this software. I was able to download a CSV file, but I could not find the skin temperature data in it. Am I doing something wrong or is it just not available? I would like to see minute based skin temperature readings along with its corresponding time-stamp. Thanks in advance.

**Comment by nachmore** [comment]
Unfortunately skin temperature is not recorded and uploaded periodically, so it is not reflected in the data we pull from the cloud :(
