### ISSUE TITLE
App Crash on Window 7 (64-bit) on startup

### ISSUE THREAD

**Issue by zslaybaugh** [nachmore/unBand#8]
When I execute the "unband.exe" and continue through the two messages (Hello, and Heads Up) the application immediately crashes on my Windows 7 SP1 (64-bit) OS with the latest Microsoft Patches.

Below are the error message details:
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	unband.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	548fdf49
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.18063
  Problem Signature 06:	526766b5
  Problem Signature 07:	26aa
  Problem Signature 08:	0
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Thanks and looking forward to using your application, also I may have time to assist further beta testing, debugging, and development.

Regards,
Zak

**Comment by zslaybaugh** [comment]
after the update seems to be working now...

**Comment by nachmore** [comment]
Awesome - thanks for the follow up!
