### ISSUE TITLE
Microsoft.Cargo.Client.Desktop8.dll

### ISSUE THREAD

**Issue by mkay12** [nachmore/unBand#89]
since the last MS band sync update the Microsoft.Cargo.Client.Desktop8.dll is missing and unband crashes on startup.
unfortunately i have no backup of this file.
Can anybody who still has it, provide it for us?

**Comment by mkay12** [comment]
i found an old version in the www and copied it to the folder, works again :-)

**Comment by jinayoon** [comment]
@mkay12 Hi! Do you have a copy of the old version you could send me? I really wanna try unBand but I can't find an old version with the Microsoft.Cargo.Client.Desktop8.dll file :( 

Please let me know! Thanks so much.
