### ISSUE TITLE
Unable to find Band Desktop app dlls

### ISSUE THREAD

**Issue by saramgsilva** [nachmore/unBand#9]
Hello,

the UnBand is crashing in Windows 10 TP and I read it

App Still Crashes on Start
------

Even though you have the Sync app installed, unBand still crashes. This is likely due to us not being able to find the Sync app.

To solve this, copy Microsoft.Cargo.Client.Desktop8.dll to c:\Program Files(x86)\Microsoft Band Sync.

You can also copy it to the same directory as unBand, search for it under %userprofile%\AppData\Local\Apps\2.0

Yup, we're going to work on a better solution...

-----

but where is the Microsoft.Cargo.Client.Desktop8.dll ?

**Comment by nachmore** [comment]
Using this bug to track the TODO to fix the hardcoded nature of the dll. We should really be pulling this from the registry:

`HKLM\SOFTWARE\MICROSOFT\Windows\CurrentVersion\Installer\UserData\[user SID]\Components\1C4501C98808F3A5CBF549E17D39406F\D9E6F917E27BA454F9E448BCA68562`

**Comment by bc3tech** [comment]
@nachmore, is there any reason you can't use the %programfiles% env variable? just curious. Registry (and, truthfully, filepath) things always seem "smelly" to me :)

**Comment by nachmore** [comment]
Simply because the user can change the install path. Pulling the path from the registry should give us a direct pointer to the file, regardless of where the app is installed, though I'll probably still have a fallback of "go look in the default location".

Obviously the hardcoded path that I have in there right now is a horrible hack...

**Comment by bc3tech** [comment]
gotchya.

**Comment by EphraimB** [comment]
Where's the new version?

**Comment by nachmore** [comment]
The new version of the Desktop Sync app refactored the base Band code, I'm working on pushing a version that works with the new dlls.

**Comment by EphraimB** [comment]
How long should I expect the new version to come out. Also, where can I find the Microsoft.Cargo.Client.Desktop8.dll? I did a whole hard drive search and no results showed up

**Comment by nachmore** [comment]
Most of the code is now in and working, I want to test the last few scenarios and push this out in the morning.

**Comment by EphraimB** [comment]
I think you should close this because there's no such thing as Microsoft.Cargo.Client.Desktop8.dll anymore

**Comment by nachmore** [comment]
There have been multiple checkins to make this more robust as well as to present user-friendly messages to explain how to fix this when this happens in the wild. Closing for now.
